### PR TITLE
Adding support for global preferences

### PR DESCRIPTION
**Pull request by Lichtjaeger**
I have added user global preferences for linting options.

### CODE REVIEW

**Comment by cfjedimaster** [comment]
Nice!

**Comment by busykai** [comment]
@cfjedimaster, could you please, in the future, ask contributors to not change line endings in the files?

**Comment by cfjedimaster** [comment]
Does it matter? (Serious question - didn't seem to matter to me and my editor.)

**Comment by busykai** [comment]
It does matter. It matters to `git blame`. When you `git bisect`, you may end up with a commit that changes [the entire file](https://github.com/Lichtjaeger/brackets-jshint/commit/03bb7dc3bef6da1ecd1849421c30a6a188671dd8#diff-7a9076d6d94e62c13d641aa71f19ae8e). Then go figure what introduced the issue (if anything). You'll have to do extra just because someone wasn't careful enough.

Most of the editors would handle line endings for you, but it's not about the editor. It's about understanding what the change was (and being respectful to others).

**Comment by Lichtjaeger** [comment]
Sorry. git-tools for brackets automaticaly cleans whitespaces and lineendings on commit.

**Pull request merged**
